datastax.astra:
    secure-connect-bundle: secure-connect.zip
    client-id: ztjgckDcmWmpcbKQqlKKPdHa
    client-secret: oKOUPd1l3Bpc8TncvG5S7J1+FaSlM1GCPus.5iChPXgsj,-hxFJYqkZBAquRTZhO67G1dH-bm0gQZx2UTYEBM5JHGjCbK_C6vTYonHW0SgMUJbiLDTUZd-ZCsG.jKEmz
 